name: Snake

on:
  schedule:
    - cron: "0 6 * * *"   # раз в день
  workflow_dispatch:      # возможность запустить руками
  push:
    branches: ["main"]    # на всякий

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: HDBOOMONE12
          outputs: |
            dist/github-snake.svg?palette=github-dark

      - name: Move file to assets
        run: |
          mkdir -p .github/assets/assets
          cp dist/github-snake.svg .github/assets/assets/github-snake.svg

      - name: Commit updated snake
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update snake"
          file_pattern: ".github/assets/assets/github-snake.svg"
